name = input("Enter your name : ")
age = input("Enter your age : ")
cgpa = input("Enter your CGPA : ")

print("-------------------")
print("Student Information")
print("-------------------")
print("Name : " + name)
print("Age  :", age)
print("CGPA :", cgpa)
